version: '3.8'

services:
  gesbackend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    restart: "always"
    networks:
      bahmni-standard_default:

networks:
  bahmni-standard_default: