version: '3.8'

services:
  cielConceptToGesApi:
    build:
      context: ./cielConceptToGesApi
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    command: ["flask", "cielConceptToGesApi.py"]
