version: '3.8'

services:
  gesbackend:
    build:
      context: ./
      dockerfile: Dockerfile
    hostname: gesbackend  
    ports:
      - "8093:8093"
    restart: "always"
    networks:
      bahmni-standard_default:
        aliases:
          - "gn_backend-alias"

networks:
  bahmni-standard_default:
   
      

